Adding Ember documentation
sstsimulator/sst-elements pull request #1948
Opened 2022-10-14 20:20 UTC by nab880

Adding ember documentation and examples

Erase this information and put your Pull Request comments here 
---

Instructions for Issuing a Pull Request to sst-elements
-------------------------------------------------------

1 - Verify that the Pull Request is targeted to the **devel** branch of sstsimulator/sst-elements

2 - Verify that Source branch is up to date with the devel branch of sst-elements

3 - After submitting your Pull Request:
   * Automatic Testing will commence in a short while 
      * Pull Requests will be tested with the devel branches of the sst-core and sst-sqe repositories
         * These branches are syncronized with the devel branch of sst-elements.  This is why is it important to keep your source branch up to date.
      * If testing passes, the source branch will be automatically merged (if possible)
         * Pull Requests from forks will not be automatically tested until the code is inspected.
         * Pull Requests from forks will not be automatically merged into the devel branch.
      * If testing fails, You will be notified of the test results.  
         * The Pull Request will be retested on a regular basis - Changes to the source branch can be made to correct problems
         
4 - DO NOT DELETE THE BRANCH (OR FORKED REPO) UNTIL THE PULL REQUEST IS MERGED.
----

2022-10-14 20:46 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

2022-10-14 21:03 UTC, jpkenny requested changes
Just fix the makefile problem and I'll release the pre-check requirement

2022-10-14 21:03 UTC, jpkenny commented on src/sst/elements/ember/Makefile.am
> +	example/motifs/emberexample.h
need the "\\" after these

2022-10-14 22:29 UTC, jpkenny commented on src/sst/elements/ember/Makefile.am
> +	example/motifs/emberexample.h
fixed with changeset [f5a4ac1](https://github.com/sstsimulator/sst-elements/pull/1948/commits/f5a4ac14692fcad873abe6a944766bceee3d4565)

2022-10-14 22:31 UTC, jpkenny approved these changes
LGTM

2022-10-14 22:46 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED by label AT: PRE-TEST INSPECTED! Autotester is Removing Label; This inspection will remain valid until a new commit to source branch is performed.

2022-10-14 22:47 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-11.6-XC13-ARM_OMPI-4.0.5_PY3.9_sst-elements</h3>
<ul>
  <li>Build Num: 83</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 696</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_Make-Dist</h3>
<ul>
  <li>Build Num: 450</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 682</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 681</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: ELEMENTS (nab880/sst-elements)</dt>
  <ul>
    <li>Branch: add-ember-documentation</li>
    <li>SHA: 5f590279d64503744e54a65b367cd131993a9d49</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: b6e8c5652bf9840e695a66fb3317290e1918f9de</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: dac3c8ecee195658341362b3a66933c770cd3271</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 28aef39f18a32c56187c443837798270c9499ac8</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: nab880
</details>
</details>

2022-10-14 23:01 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_OSX-11.6-XC13-ARM_OMPI-4.0.5_PY3.9_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 83</li>
<li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-11.6-XC13-ARM_OMPI-4.0.5_PY3.9_sst-elements/83/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 696</li>
<li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements/696/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_Make-Dist</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 450</li>
<li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_Make-Dist/450/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MT-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 682</li>
<li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MT-2/682/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MR-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 681</li>
<li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MR-2/681/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
</details>

2022-10-15 03:17 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-11.6-XC13-ARM_OMPI-4.0.5_PY3.9_sst-elements</h3>
<ul>
  <li>Build Num: 84</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 697</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_Make-Dist</h3>
<ul>
  <li>Build Num: 451</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 683</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 682</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: ELEMENTS (nab880/sst-elements)</dt>
  <ul>
    <li>Branch: add-ember-documentation</li>
    <li>SHA: 5f590279d64503744e54a65b367cd131993a9d49</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: b6e8c5652bf9840e695a66fb3317290e1918f9de</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: dac3c8ecee195658341362b3a66933c770cd3271</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 28aef39f18a32c56187c443837798270c9499ac8</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: nab880
</details>
</details>

2022-10-15 03:30 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_OSX-11.6-XC13-ARM_OMPI-4.0.5_PY3.9_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 84</li>
<li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-11.6-XC13-ARM_OMPI-4.0.5_PY3.9_sst-elements/84/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 697</li>
<li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements/697/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_Make-Dist</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 451</li>
<li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_Make-Dist/451/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MT-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 683</li>
<li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MT-2/683/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MR-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 682</li>
<li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MR-2/682/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
</details>

2022-10-15 04:20 UTC, jpkenny commented on src/sst/elements/ember/example/motifs/emberexample.h
> +class Foo : public EmberMessagePassingGenerator {
Foo -> Example
@nab880

2024-10-08 17:13 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2024-10-08 17:16 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1667</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist</h3>
<ul>
  <li>Build Num: 1072</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1625</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1625</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 197</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: ELEMENTS (nab880/sst-elements)</dt>
  <ul>
    <li>Branch: add-ember-documentation</li>
    <li>SHA: b17ed6f429f015dbb394cc97cfe1d7e0d1ffdf5a</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 2574c98896598820227190149834172b962dc3fc</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 335de84417671898414e7f4d242c5ab109d5f963</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 50a62170b3681ea20cc2f56abd2eb3911053f1fc</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: nab880
</details>
</details>

2024-10-08 17:42 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1667</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements/1667/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1072</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist/1072/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1625</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2/1625/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1625</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2/1625/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 197</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements/197/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
</details>

2024-10-08 19:05 UTC, hughes-c commented
```
In file included from example/motifs/emberexample.cc:18:
example/motifs/emberexample.h:29:9: error: expected identifier before string constant
         "ember",
         ^~~~~~~
example/motifs/emberexample.h:29:9: error: expected ',' or '...' before string constant
example/motifs/emberexample.h:34:5: error: ISO C++ forbids declaration of 'SST_ELI_REGISTER_SUBCOMPONENT_DERIVED' with no type [-fpermissive]
     );
```

2024-10-08 21:47 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1669</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist</h3>
<ul>
  <li>Build Num: 1073</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1627</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1627</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 199</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: ELEMENTS (nab880/sst-elements)</dt>
  <ul>
    <li>Branch: add-ember-documentation</li>
    <li>SHA: b17ed6f429f015dbb394cc97cfe1d7e0d1ffdf5a</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 2574c98896598820227190149834172b962dc3fc</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 335de84417671898414e7f4d242c5ab109d5f963</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 50a62170b3681ea20cc2f56abd2eb3911053f1fc</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: nab880
</details>
</details>

2024-10-08 22:12 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1669</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements/1669/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1073</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist/1073/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1627</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2/1627/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1627</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2/1627/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 199</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements/199/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
</details>

2024-10-09 02:19 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1670</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist</h3>
<ul>
  <li>Build Num: 1074</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1628</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1628</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 200</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: ELEMENTS (nab880/sst-elements)</dt>
  <ul>
    <li>Branch: add-ember-documentation</li>
    <li>SHA: b17ed6f429f015dbb394cc97cfe1d7e0d1ffdf5a</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 2574c98896598820227190149834172b962dc3fc</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 593017605bfef08f493ce894449843ef8c5d56a8</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 50a62170b3681ea20cc2f56abd2eb3911053f1fc</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: nab880
</details>
</details>

2024-10-09 02:44 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1670</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements/1670/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1074</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist/1074/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1628</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2/1628/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1628</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2/1628/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 200</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements/200/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
</details>

2024-10-09 06:49 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1671</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist</h3>
<ul>
  <li>Build Num: 1075</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1629</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1629</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 201</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: ELEMENTS (nab880/sst-elements)</dt>
  <ul>
    <li>Branch: add-ember-documentation</li>
    <li>SHA: b17ed6f429f015dbb394cc97cfe1d7e0d1ffdf5a</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 2574c98896598820227190149834172b962dc3fc</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 593017605bfef08f493ce894449843ef8c5d56a8</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 50a62170b3681ea20cc2f56abd2eb3911053f1fc</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: nab880
</details>
</details>

2024-10-09 07:15 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1671</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements/1671/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1075</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist/1075/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1629</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2/1629/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1629</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2/1629/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 201</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements/201/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
</details>

2024-10-09 11:19 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1672</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist</h3>
<ul>
  <li>Build Num: 1076</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1630</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1630</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 202</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: ELEMENTS (nab880/sst-elements)</dt>
  <ul>
    <li>Branch: add-ember-documentation</li>
    <li>SHA: b17ed6f429f015dbb394cc97cfe1d7e0d1ffdf5a</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 2574c98896598820227190149834172b962dc3fc</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 593017605bfef08f493ce894449843ef8c5d56a8</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 50a62170b3681ea20cc2f56abd2eb3911053f1fc</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: nab880
</details>
</details>

2024-10-09 11:41 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1672</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements/1672/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1076</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist/1076/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1630</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2/1630/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1630</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2/1630/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 202</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements/202/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
</details>

2024-10-09 15:49 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1673</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist</h3>
<ul>
  <li>Build Num: 1077</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1631</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1631</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 203</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: ELEMENTS (nab880/sst-elements)</dt>
  <ul>
    <li>Branch: add-ember-documentation</li>
    <li>SHA: b17ed6f429f015dbb394cc97cfe1d7e0d1ffdf5a</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 2574c98896598820227190149834172b962dc3fc</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 593017605bfef08f493ce894449843ef8c5d56a8</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 50a62170b3681ea20cc2f56abd2eb3911053f1fc</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: nab880
</details>
</details>

2024-10-09 16:13 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1673</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements/1673/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1077</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_Make-Dist/1077/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1631</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2/1631/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1631</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2/1631/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 203</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-14-XC15-ARM2_OMPI-4.1.6_PY3.10_sst-elements/203/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
</details>

2024-10-09 17:13 UTC, feldergast commented
Adding WIP to this for now to avoid blocking core PRs needed for the release

2024-10-31 13:11 UTC, feldergast commented
Converting to draft to make sure this doesn't accidentally merge.  The PR has over 700 commits in it, but only 10 changed files.  If you intend to merge it, please do a rebase against current devel.

2024-11-05 16:35 UTC, closed without merging