Update Balar with mmio interface
sstsimulator/sst-elements pull request #2078
Opened 2023-03-21 18:24 UTC by William-An

Update Balar as a mmio device, supporting both CUDA API trace-driven execution (with `balarTestCPU`) and Vanadis (break with the TLB unit right now).

2023-03-21 18:38 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

2023-03-23 23:17 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

2023-03-23 23:35 UTC, hughes-c requested changes

2023-03-23 23:35 UTC, hughes-c commented on src/sst/elements/balar/balar.cc
Instead of commenting-out unused features, please remove them.

2023-03-23 23:35 UTC, hughes-c commented on src/sst/elements/memHierarchy/tests/testStdMem-mmio.py
Please remove this file from the commit. Just checkout the current version from devel and move this test into the balar test directory if it is sufficiently different from the other two tests.

2023-03-23 23:35 UTC, hughes-c commented on src/sst/elements/vanadis/tests/small/misc/splitLoad/mipsel/splitLoad
This is a binary file. Why was it included in the commit?

2023-03-23 23:59 UTC, William-An commented on src/sst/elements/vanadis/tests/small/misc/splitLoad/mipsel/splitLoad
I think it gets included in the commit history accidentally. Should I get it removed?

2023-03-24 00:38 UTC, William-An commented on src/sst/elements/memHierarchy/tests/testStdMem-mmio.py
Done

2023-03-24 00:39 UTC, William-An commented on src/sst/elements/balar/balar.cc
Done

2023-03-24 16:31 UTC, William-An commented on src/sst/elements/balar/balar.cc
Actually those commented out section are part of the original balar. Do we want to remove all of the old code once and for all?

2023-03-24 18:11 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

2023-03-30 21:47 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

2023-03-30 21:47 UTC, William-An commented
The `balar_event.h` file still stays in the repo as `ariel.cc` depends on it. I am just including it so that no modifications will be done on ariel. All other old balar stuff should be removed now.

2023-04-03 19:21 UTC, hughes-c approved these changes

2023-04-03 19:47 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED by label AT: PRE-TEST INSPECTED! Autotester is Removing Label; This inspection will remain valid until a new commit to source branch is performed.

2023-04-03 19:48 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 980</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_Make-Dist</h3>
<ul>
  <li>Build Num: 694</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 966</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 964</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.2_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 320</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: ELEMENTS (William-An/sst-elements)</dt>
  <ul>
    <li>Branch: balar-mmio</li>
    <li>SHA: dbde9b28286c78a6252a843f4a1f04ca28b348a4</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 4c044c8d98438cee78e23b3e0cdcd65cf7ff9ab0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: e5841d3f5a7bf48da3a56aa451e17cde0c125b44</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: f4fd93b133fd6eac8ab7a9b975159b7af38a84bb</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: William-An
</details>
</details>

2023-04-03 21:13 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 980</li>
  <li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements/980/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_Make-Dist</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 694</li>
<li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_Make-Dist/694/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MT-2</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 966</li>
  <li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MT-2/966/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MR-2</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 964</li>
  <li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MR-2/964/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.2_PY3.10_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 320</li>
<li>URL: Jenkins server at https://jenkins-srn.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.2_PY3.10_sst-elements/320/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Component</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_GNA_1</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_MemPool_overflow</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_MemPool_undeleted_items</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_Messier_gupsgen</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Messier_gupsgen_2RANKS</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Messier_gupsgen_fastNVM</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Messier_stencil3dbench_messier</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Messier_streambench_messier</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_ParamComponent</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_PerfComponent</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_RNG_Marsaglia</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_RNG_Mersenne</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_RNG_xorshift</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_Samba_gupsgen_mmu</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Samba_gupsgen_mmu_4KB</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Samba_gupsgen_mmu_three_levels</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Samba_stencil3dbench_mmu</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Samba_streambench_mmu</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_SubComponent_sc_2a</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_SubComponent_sc_2u</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_SubComponent_sc_2u2a</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_SubComponent_sc_2u2u</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_SubComponent_sc_2ua</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_SubComponent_sc_2uu</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_SubComponent_sc_a</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_SubComponent_sc_u</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_SubComponent_sc_u2a</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_SubComponent_sc_u2u</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_SubComponent_sc_ua</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_SubComponent_sc_uu</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_cacheTracer_1</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_cacheTracer_2</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_cassini_prefetch_nextblock</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_cassini_prefetch_none</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_cassini_prefetch_stride</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_json_io</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_json_io_comp</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_json_io_parallel</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_python_io</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_python_io_comp</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_python_io_parallel</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_python_single_parallel_load</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_juno_modulo</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_juno_sum</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_hybridsim_hybridsim</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHSieve</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl2_1</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl3_1</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl3_2</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl3_3</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl4_1</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl4_2</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl4_2_ramulator</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl5_1</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl5_1_ramulator</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl8_1</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl8_3</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl8_4</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl9_1</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl9_2</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl_1</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl_2</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_memHierarchy_sdl_3</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_miranda_copybench</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_miranda_gupsgen</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_miranda_inorderstream</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_miranda_randomgen</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_miranda_revsinglestream</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_miranda_singlestream</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_miranda_stencil3dbench</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_miranda_streambench</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_prospero_binary_using_PIN_traces</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_prospero_binary_using_TAR_traces</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_prospero_binary_withtimingdram_using_PIN_traces</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_prospero_binary_withtimingdram_using_TAR_traces</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_prospero_compressed_using_PIN_traces</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_prospero_compressed_using_TAR_traces</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_prospero_compressed_withtimingdram_using_PIN_traces</td>
    <td>SKIP [...]

2023-04-04 19:54 UTC, gvoskuilen commented
@William-An I suspect the failures will be fixed by (1) merging the latest devel branch into yours or rebasing on the latest devel branch and (2) check that any new files you have added in this PR are also added to a Makefile.am. You can also run "make dist" on your branch and see which files are missing from the distribution.

2023-04-04 21:54 UTC, William-An commented
The `make dist` failed as I have changed the name of one configuration file. Now it should be fixed.

2023-04-06 18:31 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2023-04-06 18:31 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED by label AT: PRE-TEST INSPECTED! Autotester is Removing Label; This inspection will remain valid until a new commit to source branch is performed.

2023-04-06 18:32 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 986</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_Make-Dist</h3>
<ul>
  <li>Build Num: 696</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 972</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 970</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.2_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 326</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: ELEMENTS (William-An/sst-elements)</dt>
  <ul>
    <li>Branch: balar-mmio</li>
    <li>SHA: 47a5e6cd7946b0f1bac109b958be991fb5f8b02f</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 4c044c8d98438cee78e23b3e0cdcd65cf7ff9ab0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 5dfeedf8e0c92bbfc68add6956a3dd5b3e8dc434</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: f4fd93b133fd6eac8ab7a9b975159b7af38a84bb</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: William-An
</details>
</details>

2023-04-06 20:03 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 986</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_Make-Dist</h3>
<ul>
  <li>Build Num: 696</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 972</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 970</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.2_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 326</li>
  <li>Status: PASSED</li>
</ul>
</table>
</details>

2023-04-06 20:03 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2023-04-06 20:04 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-04-07 00:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-04-07 04:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-04-07 08:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-04-07 12:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-04-07 14:46 UTC, hughes-c approved these changes

2023-04-07 14:47 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ hughes-c ]!

2023-04-07 14:47 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request will be Automerged

2023-04-07 14:47 UTC, merged

2023-04-07 14:47 UTC, sst-autotester commented
Merge on Pull Request# 2078: IS A SUCCESS - Pull Request successfully merged